### ISSUE TITLE
Implement Composite Primary Keys

### ISSUE THREAD

**Issue by Trojaner25** [Static-Interface/Sink-Plugins#19]
Because @Shadow1Raven  is too lazy

**Comment by Shadow1Raven** [comment]
pls

**Comment by rinukkusu** [comment]
Just do it!!
Make your dreams come true!

Am 17. September 2015 14:42:45 MESZ, schrieb Shadow Raven <notifications@github.com>:
>pls
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Static-Interface/Sink-Plugins/issues/19#issuecomment-141069084

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
